language: ruby
env:
 DB=postgres
 RAILS_ENV=test
before_install:
- "cd example"
install:
- "bundle install"
before_script:
- "bundle exec rake db:create db:schema:load db:test:prepare"
script:
- "bundle exec rspec --color --format documentation --require spec_helper --require rails_helper"
